### ISSUE TITLE
Possible feature request: Decode without clearing state

### ISSUE THREAD

**Issue by crumblingstatue** [sile/amf#4]
While developing my .sol editor, I encountered a few .sol files where decoding an AMF3 object
resulted in an `OutOfRangeReference` error. While trying to debug, I eventually had the idea that 
these AMF objects might be referring to previously read traits/strings/complexes, which are discarded when you call `decode()`.
I made a new function which omits the discard code.
```Rust
    /// Decodes a AMF3 value. Keeps traits/strings/complexes.
    pub fn decode_keep_state(&mut self) -> DecodeResult<Value> {
        self.decode_value()
    }
```
If I call it instead of `decode()`, these files seem to read just fine.

The question is, am I assuming this correctly, or could something else cause this `OutOfRangeReference` error? Before I submit a pull request, I thought I would ask your expert opinion, as I don't fully understand the AMF3 format.

Here is one such file, which seems to be a cookie for an online flash game:
```
00000000  00 bf 00 00 01 c4 54 43  53 4f 00 04 00 00 00 00  |......TCSO......|
00000010  00 09 61 6e 61 6c 79 74  69 63 73 00 00 00 03 09  |..analytics.....|
00000020  75 74 6d 61 0a 0b 01 17  63 75 72 72 65 6e 74 54  |utma....currentT|
00000030  69 6d 65 05 41 d7 63 3f  6d 00 00 00 19 73 65 73  |ime.A.c?m....ses|
00000040  73 69 6f 6e 43 6f 75 6e  74 04 02 15 65 78 70 69  |sionCount...expi|
00000050  72 61 74 69 6f 6e 08 01  42 77 c1 e2 15 f0 c0 00  |ration..Bw......|
00000060  11 63 72 65 61 74 69 6f  6e 08 01 42 76 d6 eb f0  |.creation..Bv...|
00000070  70 c0 00 13 66 69 72 73  74 54 69 6d 65 05 41 d7  |p...firstTime.A.|
00000080  63 3d e2 c0 00 00 11 6c  61 73 74 54 69 6d 65 05  |c=.....lastTime.|
00000090  41 d7 63 3d e2 c0 00 00  15 64 6f 6d 61 69 6e 48  |A.c=.....domainH|
000000a0  61 73 68 04 b6 8a e4 8f  13 73 65 73 73 69 6f 6e  |ash......session|
000000b0  49 64 05 43 cb e2 a7 3a  88 3a b2 01 00 09 75 74  |Id.C...:.:....ut|
000000c0  6d 7a 0a 01 21 63 61 6d  70 61 69 67 6e 54 72 61  |mz..!campaignTra|
000000d0  63 6b 69 6e 67 06 81 27  75 74 6d 63 73 72 3d 63  |cking..'utmcsr=c|
000000e0  6f 6f 6c 6d 61 74 68 67  61 6d 65 73 2e 63 6f 6d  |oolmathgames.com|
000000f0  7c 75 74 6d 63 63 6e 3d  28 72 65 66 65 72 72 61  ||utmccn=(referra|
00000100  6c 29 7c 75 74 6d 63 6d  64 3d 72 65 66 65 72 72  |l)|utmcmd=referr|
00000110  61 6c 7c 75 74 6d 63 63  74 3d 2f 30 2d 63 6c 69  |al|utmcct=/0-cli|
00000120  63 6b 65 72 2d 68 65 72  6f 65 73 21 63 61 6d 70  |cker-heroes!camp|
00000130  61 69 67 6e 53 65 73 73  69 6f 6e 73 04 02 1b 72  |aignSessions...r|
00000140  65 73 70 6f 6e 73 65 43  6f 75 6e 74 04 02 08 08  |esponseCount....|
00000150  01 42 76 d6 eb f0 71 20  00 21 63 61 6d 70 61 69  |.Bv...q .!campai|
00000160  67 6e 43 72 65 61 74 69  6f 6e 05 41 d7 63 3f 6d  |gnCreation.A.c?m|
00000170  00 00 00 0e 04 b6 8a e4  8f 06 08 01 42 77 11 a9  |............Bw..|
00000180  79 d1 20 00 01 00 09 75  74 6d 62 0a 01 06 08 01  |y. ....utmb.....|
00000190  42 76 d6 ed a7 e5 a0 00  08 08 01 42 76 d6 eb f0  |Bv.........Bv...|
000001a0  71 a0 00 0c 05 41 d7 63  3d e2 c0 00 00 15 74 72  |q....A.c=.....tr|
000001b0  61 63 6b 43 6f 75 6e 74  04 02 0e 04 b6 8a e4 8f  |ackCount........|
000001c0  0b 74 6f 6b 65 6e 04 0a  01 00                    |.token....|
000001ca
```
If needed, I can send you the raw file in email, which you can read with my program: https://github.com/crumblingstatue/soledit

**Comment by sile** [comment]
This is a somewhat interesting issue. Please let me consider the feasibility of this feature this weekend.

**Comment by sile** [comment]
I found a description about reference table in [AMF 3 specification](https://www.adobe.com/content/dam/acom/en/devnet/pdf/amf-file-format-spec.pdf) as below.

> Similar to AFM 0, AMF 3 object reference tables, object trait reference tables and string reference tables must be reset each time a new context header or message is processed.
> -- 4.1 NetConnection and AMF 3

I think that it means that `{amf0,amf3}::Decoder::decode` methods should not clear the reference tables automatically after decoding **a value** (so the current implementation seems wrong...).

IMO, it seems better to split the current decode method into two methods as follows:
```rust
impl Decoder {
    pub fn decode(&mut self) -> DecodeResult<Value> {
        self.decode_value()
    }

   pub fn clear_reference_tables(&mut self) {
        self.traits.clear();
        self.strings.clear();
        self.complexes.clear();
   }
}
```

What do you think of it? > @crumblingstatue

**Comment by crumblingstatue** [comment]
That looks good to me, it would be nice, thank you!

**Comment by sile** [comment]
Thank you for your swift reply. I created #5 to reflect the above idea.

**Comment by sile** [comment]
Published: https://crates.io/crates/amf/0.3.0

**Comment by crumblingstatue** [comment]
Thank you very much!
